apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: koa-app-monitor
  namespace: monitoring
  labels:
    app: koa-app
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - application
  selector:
    matchLabels:
      app: koa-app
  endpoints:
  - port: koa-port
